export const SET_SORT_BY = 'SET_SORT_BY'
export const SET_CATEGORY = 'SET_CATEGORY'
export const SET_DATA = 'SET_DATA'
export const DATA_LOADED = 'DATA_LOADING'
export const ADD_DATA_TO_CART = 'ADD_DATA_TO_CART'